version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/a-hilaly/memecache

    steps:
      - checkout
      
      - run:
          name: test package
          command: |
            go test -v -bench .