version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/a-hilaly/memecache

    steps:
      - checkout
      
      - run:
          name: test package
          command: |
            go test -v -race -coverprofile=coverage.txt
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN